[package]
name = "pdf-thing"
version = "0.1.0"
authors = ["Alexei Paksevatkin <ne.eshte@otso.city>"]
edition = "2018"

[dependencies]
printpdf = "0.2.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_repr = "0.1"